add fallback build ci/cd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,6 +25,16 @@ jobs:
           echo "Listing files"
           ls -la
 
-          docker compose -f docker-compose.prod.yml down || true
-          docker compose -f docker-compose.prod.yml build
-          docker compose -f docker-compose.prod.yml up -d
+          echo "🔨 Building new image..."
+          if docker compose -f docker-compose.prod.yml build; then
+            echo "✅ Build success"
+
+            echo "🚀 Restarting container..."
+            docker compose -f docker-compose.prod.yml up -d
+
+            echo "🎉 Deploy success"
+          else
+            echo "❌ Build failed!"
+            echo "⚠️ Keeping previous running container"
+            exit 1
+          fi
